tracking_level:
  type: string
  default: 1

tracking_icon:
  type: string
  default: d-regular

mute_level:
  type: string
  default: 0

mute_icon:
  type: string
  default: d-muted

include_subcategories:
  default: true
